/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "977bae7b294a909f4006acced7e70f02bee3d010"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
